name: Listar e analisar imagens Docker
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image_version:
        description: 'versão da imagem que será baixada pelo docker'
        default: 'jpdiasdocker/api-contas:1.0.1'
  
env:
  - image-name: {{inputs.image}}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Configuracao inicial do Docker
        uses: docker/setup-docker-action@v5
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: listar variavel da image
        run: echo $image_version



