name: Listar e analisar imagens Docker
on:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'versao da imagem que sera baixada pelo docker'
        default: 'jpdiasdocker/api-contas:1.0.1'
        required: true
        type: string
env:
  REGISTRY: docker.io
  COMPARE_TAG: latest        

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Configuracao inicial do Docker
        uses: docker/setup-docker-action@v5
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: listar variavel da image
        run: echo the image is ${{inputs.image_version}}

      - name: Pull Docker image # api-contas
        run:  docker pull ${{inputs.image_version}}

      - name: lista imagens docker locais
        run: docker image ls

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          only-fixed: true

