name: Primeiro Workflow  Linuxtips

on:
  push:
    branches:
      - master

jobs:
  giropops:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do ubuntu
        run: cat /etc/os-release

      - name: Exibit uma mensagem
        run: echo  "Estou Fazendo o curso guthub Action da Linuxtips"
